name: 'Folder Watcher'
inputs:
  folder-name:
    description: 'The name of the folder that we want to watch.'
    required: true
    default: 'templates'
runs:
  using: "composite"
  steps:
    - name:
      run: "echo 'There was a change in this folder: <p><span style='font-weight: bold;'>$INPUT_FOLDER</span></p>.'"
      shell: bash
      env:
        INPUT_FOLDER: ${{ inputs.folder-name }}