name: 'Folder Watcher'
inputs:
  folder-name:
    description: 'The name of the folder that we want to watch.'
    required: true
    default: 'templates'
runs:
  using: "composite"
  steps:
    - name:
      run: echo -e "There was a change in this folder \033[1m$INPUT_FOLDER"
      shell: bash
      env:
        INPUT_FOLDER: ${{ inputs.folder-name }}