name: Folders Check
run-name: Checking if there's a change in folders
on:
    push:
        paths: ['templates/**', 'public/css/**']

jobs:
  change-watcher:
    runs-on: ubuntu-latest
    outputs:
      path1: ${{ steps.filter.outputs.path1 }}
      path2: ${{ steps.filter.outputs.path2 }}
    steps:
      - uses: actions/checkout@v4

      # https://github.com/marketplace/actions/paths-changes-filter#examples
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            path1:
              - 'templates/**'
            path2:
              - 'public/css/**'
          cache: 'npm'

  templates-watcher:
    needs: change-watcher
    name: Templates folder watcher
    # run only if 'templates' files were changed
    if: ${{ needs.change-watcher.outputs.path1 == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/folder-watcher
        with:
          folder-name: 'templates'

  css-watcher:
    needs: change-watcher
    name: Templates folder watcher
    # run only if 'public/css/**' files were changed
    if: ${{ needs.change-watcher.outputs.path2 == 'true'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/folder-watcher
        with:
          folder-name: 'public/css/**'

