name: Folders Check
run-name: Checking if there's a change in folders
on:
    push:
        paths: ['templates/**', 'public/css/**']

jobs:
  templates-watcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            path1:
              - 'templates/**'
            path2:
              - 'public/css/**'

      # run only if 'templates' files were changed
      - name: Templates folder watcher
        if: steps.filter.outputs.path1 == 'true'
        uses: ./.github/actions/folder-watcher
        with:
          folder-name: 'templates'

      # run only if 'public/css/' files were changed
      - name: CSS folder watcher
        if: steps.filter.outputs.path2 == 'true'
        uses: ./.github/actions/folder-watcher
        with:
          folder-name: 'public/css/'

