name: Folders Check
run-name: Checking if there's a change in folders
on:
    push:
        paths: ['templates/**', 'public/css/**']
jobs:
  templates-watcher:
    runs-on: ubuntu-latest
    steps:
      - name: Templates watcher
        run: echo ${{ github.repository }}
        # uses: ./.github/actions/folder-watcher
        # with:
        #   folder-name: 'templates'

