name: Index Listener
run-name: Index Listener
on:
  push:
    paths: ['templates/index.html']
jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Index Listener Check
        run: echo "The index.html changed."